language: node_js
node_js:
  - stable
cache: npm
install:
  - npm install
  - npm run build

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: npm run cover
    - stage: npm release
      if: tag IS blank
      node_js: stable
      script: gulp build
      before_deploy:
        - cd dist
        - npm install
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        tag: next
        on:
          branch: master
    - stage: npm latest release
      if: tag IS present
      node_js: stable
      script: gulp build
      before_deploy:
        - cd dist
        - npm install
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        tag: latest
        on:
          tags: true

after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"