language: node_js
node_js:
  - stable
cache: npm
install:
  - npm install
  - npm run build

jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: npm run cover
      after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"

    - stage: npm release
      node_js: stable
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        tag: latest
        on:
          tags: true
